name: CI
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # 沒有 lockfile 時用 npm i
      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund
      - name: Compile (Hardhat)
        run: npx hardhat compile
      - name: List contracts
        run: ls -la contracts || true
