name: Validate Telegram Links
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run validator
        run: node tools/validate-telegram-links.mjs
