name: Validate Telegram Links

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run validator
        run: node tools/validate-telegram-links.mjs
